version: '3.8'

services:
  -s-status:
    container_name: -s-status-dev
    image: cyronia/-s-status:nightly2
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3002:3002"  # <Host Port>:<Container Port>
      - "3307:3306"

